-numPy
-pandas
-matplotlib and seaborn 
-eda,data transformation,feature engineering
-model training using Logistic Regression, Random forest, support vector machine,voting classifier 
-evaluation
-cross-validation also hyperparametertuning 

why numpy is faster than pure python?
- it stores numbers in a contigious location-next to each other 
- typechecking and typecasting is internally performed while we do list operation but we can store single data types elements in numpy
-numpy is implemented in c so heavy computation task is done at a compiled time

In [13]:
import time
start=time.time()
list=[1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20]
for i in list:
    print(i*2)
end=time.time()
print(end-start)
    
    

2
4
6
8
10
12
16
18
20
22
24
26
28
30
32
34
36
38
40
0.002016305923461914


In [ ]:
import numpy as np
start=time.time()
arr1=np.array(list)

arr2=arr1*2
print(arr2)
end=time.time()
print(end-start)




[ 2  4  6  8 10 12 16 18 20 22 24 26 28 30 32 34 36 38 40]
0.0006394386291503906


In [19]:
# Array creation in numpy
arr1=np.array(list)
print(arr1.ndim)
print(arr1.dtype)

1
int64


In [21]:
list2=[
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]
arr2=np.array(list2)
print(arr2.ndim)
print(arr2.shape)

2
(3, 4)


In [24]:
# zeros and ones
arr3=np.zeros(5) # 1D array with 5 elements
print(arr3)


[0. 0. 0. 0. 0.]


In [25]:
arr4=np.zeros((3,4)) # 2D array with 3 rows and 4 columns
print(arr4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [32]:
arr5=np.ones(5) # 1D array with 5 elements
print(arr5)
arr6=np.ones((3,4)) # 2D array with 3 rows and 4 columns
print(arr6)
print(arr6.ndim)
print("-"*50)

arr7=np.ones((2,3,4)) # 3D array with 2 blocks, 3 rows and 4 columns
print(arr7)
print(arr7.ndim)
print(arr7.shape)


[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
2
--------------------------------------------------
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3
(2, 3, 4)


In [38]:
# pass custom value
arr8=np.full(shape=5,fill_value=5) # 1D array with 5 elements
arr9=np.full(shape=(2,3),fill_value=5) # 1D array with 5 elements
print(arr8)
print(arr9)

arr0=np.full(shape=(2,3,5),fill_value=5)
print(arr0)
print(arr0.ndim)
print(arr0.shape)

[5 5 5 5 5]
[[5 5 5]
 [5 5 5]]
[[[5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]]

 [[5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]]]
3
(2, 3, 5)


In [ ]:
## create array with range of values
arr1=np.arange(1,11,1) # start , end , step
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [42]:
arr1=np.linspace(1,10,5) # start , end , number of values
print(arr1)

[ 1.    3.25  5.5   7.75 10.  ]


In [45]:
arr1=np.diag([1,2,3,4,5]) # diagonal matrix
print(arr1)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [47]:
# indentity matrix
arr2=np.identity(5) # 5x5 identity matrix
print(arr2)
arr1=np.eye(5) # 5x5 identity matrix
print(arr1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [55]:
arr1=np.random.rand(5,2,3) # 5x2x3 matrix with random values between 0 and 1
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[[[0.1039919  0.50032572 0.48589776]
  [0.6300261  0.27312614 0.23986474]]

 [[0.16699393 0.0351756  0.51557689]
  [0.98597027 0.92294253 0.44983399]]

 [[0.41721994 0.86388842 0.93014365]
  [0.40972917 0.867831   0.90049853]]

 [[0.86447071 0.38438146 0.83951082]
  [0.95529656 0.01776613 0.18497909]]

 [[0.18660721 0.76302852 0.43834663]
  [0.18085635 0.79138509 0.745132  ]]]
3
(5, 2, 3)


In [58]:
arr1=np.random.randint(low=2, high=10, size=(5,2,3)) # 5x2x3 matrix with random values between 2 and 10
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[[[6 7 2]
  [4 8 5]]

 [[6 4 8]
  [7 3 3]]

 [[3 3 2]
  [3 9 8]]

 [[4 9 9]
  [2 5 9]]

 [[5 9 2]
  [7 9 5]]]
3
(5, 2, 3)


In [ ]:
# indexing and slicing in numpy arrays