In [1]:
import numpy as np

In [2]:
# indexing and slicing in numpy arrays

In [ ]:
# press ctrl + /
# indexing=accessing individual elements of an array
# slicing =accessing a range of elements in an array

In [3]:
# indexing in 1d array
arr1=np.array([10,20,30,40,50,60,70,80,90,100])
print(arr1)

[ 10  20  30  40  50  60  70  80  90 100]


In [7]:
arr1[-1]

np.int64(100)

In [8]:
#indexing in 2d array
arr2=np.random.randint(low=1,high=20,size=(4,4))
print(arr2)

[[17 14 19 15]
 [ 7 10 16 19]
 [ 9 17 17 15]
 [13 12 18  9]]


In [ ]:
arr2[1,1] #arr[row position,column position]

np.int32(10)

In [11]:
arr2[3,-1] 

np.int32(9)

In [12]:
## slicing in 1d array
arrs=np.array([10,20,30,40,50,60,70,80,90,100])
print(arrs)

[ 10  20  30  40  50  60  70  80  90 100]


In [14]:
#syntax: arr[start:stop:step]
arrs[:2]

array([10, 20])

In [ ]:
# print [10,30,50,70,90]
arrs[::2] #arrs[0:-1:2]

array([10, 30, 50, 70, 90])

In [18]:
#slicing in 2d array
arrs2d=np.random.randint(1,50,(5,5))
print(arrs2d)

[[16 28  2 34 25]
 [38 13 10 31 33]
 [22 47  5  7 40]
 [43 31  9 27 28]
 [ 3 47 27 49 39]]


In [21]:
# [[5 7]
#  [9 27]]

arrs2d[2:4,2:4] # syntax arr[row,column]

array([[ 5,  7],
       [ 9, 27]], dtype=int32)

In [23]:
arrs2d[2:4,2:-1] # syntax arr[row,column]

array([[ 5,  7],
       [ 9, 27]], dtype=int32)

In [25]:
# [[27 28]
#  [49 39]]
arrs2d[3::,3::]

array([[27, 28],
       [49, 39]], dtype=int32)

In [26]:
arrs2d[3:5,3:5]

array([[27, 28],
       [49, 39]], dtype=int32)

In [37]:
arr3d=np.random.randint(1,100,(4,3,3))
print(arr3d)

[[[86  2 88]
  [90 73 52]
  [75 81 81]]

 [[66 23 36]
  [ 2 98 19]
  [ 6 65 97]]

 [[ 8 47 20]
  [25 63  4]
  [30 30 15]]

 [[59  3 89]
  [39 27 67]
  [27  5 24]]]


In [ ]:
# [98 19] ## press alt + shift + downarrow to copy the line
# [65 97]
arr3d[1:2,1:,1:] 


array([[[98, 19],
        [65, 97]]], dtype=int32)

In [39]:
arr3d[1,1:3,1:3]

array([[98, 19],
       [65, 97]], dtype=int32)

In [40]:
arr3d[1,1:,1:]

array([[98, 19],
       [65, 97]], dtype=int32)

In [36]:
print(arr3d.ndim)

3


In [42]:
arr2=np.random.randint(low=1,high=20,size=(4,4))
print(arr2)

[[ 4 11 18 16]
 [18 19  2  6]
 [17 11  3 10]
 [17  5 12 14]]


In [ ]:
# # retrieve corner elements
# [[4  16]
#  [17  14]]

In [44]:
arr2[::3,::3]
 

array([[ 4, 16],
       [17, 14]], dtype=int32)

In [45]:
arr2[:2:,::3]

array([[ 4, 16],
       [18,  6]], dtype=int32)

In [46]:
arr2[0:-1:3,-1:-1:3]

array([], shape=(1, 0), dtype=int32)

In [47]:
print(arr2)

[[ 4 11 18 16]
 [18 19  2  6]
 [17 11  3 10]
 [17  5 12 14]]


In [49]:
arr2[[0,-1]]

array([[ 4, 11, 18, 16],
       [17,  5, 12, 14]], dtype=int32)

In [50]:
arr2[[0,-1]][:,[0,-1]]

array([[ 4, 16],
       [17, 14]], dtype=int32)

In [51]:
arr2

array([[ 4, 11, 18, 16],
       [18, 19,  2,  6],
       [17, 11,  3, 10],
       [17,  5, 12, 14]], dtype=int32)

In [ ]:
arrp=arr2[[0,-1]]
print(arrp)

[[ 4 11 18 16]
 [17  5 12 14]]


In [56]:
arrp[0:2,[0,-1]] #arrp[rows,columns]

array([[ 4, 16],
       [17, 14]], dtype=int32)

In [66]:
## Numpy attributes and methods
arrna=np.random.randint(1,5,(4,5))
print(arrna)

[[4 2 2 3 4]
 [2 1 3 4 4]
 [4 1 4 2 1]
 [1 3 2 2 2]]


In [80]:
print(arrna.shape)
print(arrna.ndim)
print(arrna.size)
print(arrna.min())
print(arrna.max())
print(arrna.sum())
print(arrna.sum(axis=0)) #column wise sum
print(arrna.sum(axis=1)) #row wise sum
print(arrna.max(axis=1)) #row wise max
print(arrna.max(axis=0)) #column wise max
print(arrna.argmax(axis=0)) #column wise max
print(arrna.argmax(axis=1)) #row wise max
print(arrna.argmax(axis=1)) #row wise max
print(arrna.flatten()) #nd to 1d array

#to perform reshaping 
# 4x5=20----->10x2,2x10,5x4
print(arrna.reshape(2,10)) #reshaping

print(arrna.reshape(-1)) #change nd array to 1darray using reshaping

print(arrna.T) #transpose of an array






(4, 5)
2
20
1
4
51
[11  7 11 11 11]
[15 14 12 10]
[4 4 4 3]
[4 3 4 4 4]
[0 3 2 1 0]
[0 3 0 1]
[0 3 0 1]
[4 2 2 3 4 2 1 3 4 4 4 1 4 2 1 1 3 2 2 2]
[[4 2 2 3 4 2 1 3 4 4]
 [4 1 4 2 1 1 3 2 2 2]]
[4 2 2 3 4 2 1 3 4 4 4 1 4 2 1 1 3 2 2 2]
[[4 2 4 1]
 [2 1 1 3]
 [2 3 4 2]
 [3 4 2 2]
 [4 4 1 2]]


In [72]:
print(arrna)

[[4 2 2 3 4]
 [2 1 3 4 4]
 [4 1 4 2 1]
 [1 3 2 2 2]]


In [ ]:
# concatenation in numpy 
# we will perform few numpy exercises
# pandas 