In [2]:
#1. create a null vector of size 6
import numpy as np

In [9]:
#2. create a null vector of size 6 and the fifth value as 10
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [11]:
#3.create a vector with values ranging from 10 to 49
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
#4. reverse a vector (first element becomes last)
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [13]:
#5.create a 3x3 matrix with values ranging from 0 to 8
b=np.arange(0,9).reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
#6.creata a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#7.create a 5x5 array with random values and find the minimum and maximum values
a=np.random.random((5,5))
print(a)
print(a.min(), a.max())



[[0.11332674 0.24671623 0.37908624 0.64346132 0.23679519]
 [0.49047924 0.79132734 0.81621547 0.7595171  0.22682163]
 [0.8316418  0.86152995 0.47167353 0.97477324 0.54308566]
 [0.53641233 0.91417993 0.13135458 0.2856582  0.09192972]
 [0.25208006 0.82367101 0.64903167 0.99339601 0.14347519]]
0.09192971680198503 0.9933960074232806


In [3]:
#8.create a vector of size 30 and find the mean value
np.arange(30).mean()

np.float64(14.5)

In [ ]:
#9.create a 2d array with 1 on the border and 0 inside of shape 5x5
##[[1 1 1 1 1]
## [1 0 0 0 1]
## [1 0 0 0 1]
## [1 0 0 0 1]
## [1 1 1 1 1]]

## 5minutes

In [ ]:
##-create a 5x5 array of zeros/ones use slicing technique


In [8]:
one_v=np.ones((5,5))
one_v[1:-1,1:-1]=0
one_v
 

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
zero=np.zeros((5,5))
print(zero)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
zero[[0,-1]]=1
print(zero)

[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]


In [14]:
zero[:,[0,-1]]=1 #syntax:a[row_slicing, column_slicing]
print(zero)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
# 10
print(0 * np.nan)

nan


In [16]:
print(0.0 / 0.0)

ZeroDivisionError: float division by zero

In [17]:
print(np.nan == np.nan)

False


In [18]:
print(3- np.nan)

nan


In [19]:
print(np.inf > np.nan)

False


In [21]:
print(0.3==3*0.1)

False


In [22]:
print(3*0.1)

0.30000000000000004


In [23]:
#11.create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [26]:
# [[0 0 0 0 0]
#  [1 0 0 0 0]
#  [0 2 0 0 0]
#  [0 0 3 0 0]
#  [0 0 0 4 0]]

In [34]:
np.diag([1,2,3,4],k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [40]:
#12. create a random vector of size 10 and sort it
a=np.random.random(10)
print(a)
print(np.sort(a))

[0.54551966 0.50558422 0.95044426 0.67503051 0.72808588 0.00154146
 0.74281324 0.97338785 0.05439627 0.76067126]
[0.00154146 0.05439627 0.50558422 0.54551966 0.67503051 0.72808588
 0.74281324 0.76067126 0.95044426 0.97338785]


In [41]:
#13. make an array immutable
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [48]:
a[2]=10
print(a)
a.flags.writeable=False
a[2]=20
print(a)


[ 1  2 10  4]


ValueError: assignment destination is read-only

In [45]:
b=tuple(a)
print(b)

(np.int64(1), np.int64(2), np.int64(10), np.int64(4))


In [46]:
type(b)

tuple

In [47]:
b[0]=5
print(b)

TypeError: 'tuple' object does not support item assignment

In [ ]:
# pandas  
# creating series and DataFrame
# we will perform indexing and slicing using loc and iloc 
# we will contenation and joins in pandas
# we will also describe some of the pandas attributes and methods
# we will work on one datasts that we will do complete workflow about data cleaning--handling missing values, outliers, duplicate data, etc
# after that we will do analysis and visualization of the dataset
# after that we will perform scaling and normalization 
# model training and evaluation
# cross validation and hyperparameter tuning
# we will perform prediction pipeline 
# we will also discuss how to save and load the model using pickle and joblib